src/App.js, src/Pages/Login.js, src/index.js, src/reducers/index.js, src/store/index.js
=> [GROUP 29] requisito 1

src/App.js, src/actions/index.js, src/actions/user.js, src/index.js, src/pages/Login.js, src/reducers/User.js, src/reducers/index.js, src/store/index.js
=> Main Group 36 - elisa-login-page

src/App.css, src/App.js, src/Components/LoginForm.js, src/Pages/Login.js
=> [Main Group 6] - Requirement nº 1 - all together

src/App.js, src/actions/index.js, src/index.js, src/pages/Login.js, src/reducers/Login.js, src/reducers/index.js, src/store/index.js
=> [GRUPO 18 ] Cria tela de login

src/App.js, src/index.js, src/services/tokenAPI.js
- Pasta Pages
- Criação das rotas no App.js e no Index.js
- Criação Pages
- Criação da função da requisição do token
=> [Grupo 35] Criação das rotas e da requisição da API do token

src/App.js, src/actions/index.js, src/index.js, src/pages/Login/index.js, src/reducers/index.js, src/reducers/player.js, src/store/index.js
**o que foi feito**
- configurando o Router;
- configurando o Redux;
- criando a pagina de login;
=> [Group - 3] Luiz - Bruna - Erling - Gusta

package-lock.json, src/App.js, src/index.js, src/pages/Login.js, src/pages/login.css
- Criação dos componentes da pagina login
- Criação do handler dos componentes e controle de estado
- Criação da funcao que valida se ambos os componentes estao preenchidos para habilitar o botao.
- Estilo da pagina
=> Criação Login

README.md, src/App.js, src/Pages/Login.js, src/actions/index.js, src/helpers/index.js, src/index.js, src/reducers/users.js, src/store/index.js
O que foi feito:
* Criado arquivo de helpers com requisição a API para os Tokens;
* Token da requisição da API é armazenado no local storage.
=> [Group 29] Add token to local storage

src/actions/index.js, src/index.js, src/reducers/asyncReducer.js, src/reducers/asyncToken.js, src/store/index.js
=> [ GROUP-15 ] [ INSTALL REDUX ]

src/App.js, src/Pages/Login.js, src/actions/actionsTypes.js, src/actions/index.js, src/index.js, src/reducers/index.js, src/reducers/login.js, src/reducers/token.js, src/store/index.js
- Estrutura do Redux
- Criação do Dispatch do Email e do name para o Store
=> [Grupo 35] - Criação do Redux

cypress/integration/project.spec.js, src/components/Header/index.js, src/components/index.js, src/pages/FeedBack/index.js, src/pages/Game/index.js, src/pages/Login/index.js, src/pages/index.js, src/routes/index.js, src/services/index.js, src/store/ducks/initialState.js, src/store/ducks/player/actions.js, src/store/ducks/player/index.js, src/store/ducks/player/types.js, src/store/ducks/rootReducer.js, src/store/index.js
Requisito 2- ok e com proptypes
=> Main group 27 req 2

src/App.js, src/Components/LoginForm.js, src/Pages/Login.js, src/Pages/Settings.js
=> Requirement nº 3 - all together

src/App.js, src/actions/index.js, src/actions/user.js, src/pages/Login.js, src/reducers/index.js, src/reducers/user.js, src/store/index.js
=> [Main group 36][Requisito 1]

src/pages/Login.jsx, src/services/api.js
=> [Main group 19] Requisicao API

src/App.js, src/index.js, src/pages/Login.js, src/reducers/index.js, src/routes/index.js, src/store/index.js
Criação da tela de Login e da estrutura padrão de Redux
=> feat: login

src/App.js, src/index.js, src/pages/Login.js, src/pages/Settings.js
Criado botão para a página de configurações.
=> [Grupo 18] [Requisito 03] [Criar botão para página de configurações]

src/App.js, src/components/Header.js, src/pages/Game.js, src/redux/reducers/index.js, src/redux/store/index.js, src/services/gravatarAPI.js
=> [main group 7] req 4

src/App.js, src/Components/SettingsButton.js, src/Pages/Login.js, src/Pages/Settings.js
- Settings Button;
- Page Settings;
- Title;
=> Main group 35 button settings

src/pages/Login.js, src/pages/Settings.js, src/routes/index.js
Execução do requisito 3 - Grupo 20
=> Primeira tentativa - Requisito 3

src/App.js, src/pages/Game.js, src/pages/Login.js, src/pages/index.js, src/redux/actions/index.js, src/redux/reducers/player.js
- adição do token no localStorage
- redirecionamento para pagina do jogo
=> [Grupo 21] Requisito 2 - localStorage

cypress/integration/project.spec.js, src/App.js, src/pages/Config.js, src/pages/Login.js
Requisito onde é criado um botão que leva a tela de configuração do jogo
=> [GRUPO 17] Req. 3 Config button

src/App.js, src/actions/index.js, src/components/Trivia.js, src/index.js, src/pages/Game.js, src/pages/Login.js, src/reducers/index.js, src/reducers/receiveToken.js, src/services/triviaAPI.js, src/store/index.js
Membros: Herika Strongreen, Jessica de Paula, Rafael Alstent, André Menezes.
=> Abrindo PR: Grupo 23

src/App.js, src/Routes.jsx, src/index.js, src/pages/Login.jsx, src/redux/actions/index.js, src/redux/reducers/index.js, src/redux/reducers/login.js, src/redux/store/index.js
=> Main group 12 tela de login

src/pages/Login/index.js, src/pages/Settings/index.js, src/pages/index.js, src/routes/index.js
=> Main group 27 req 3

src/App.js, src/pages/Login.js, src/pages/Settings.js
Grupo 23 Requisito 3 Feito Eslint ok Cypress ok
=> Main group 23 requisito 3

src/pages/GameScreen.js, src/services/api.js, src/store/ducks/QuestionsRequest/actions.js, src/store/ducks/QuestionsRequest/index.js, src/store/ducks/QuestionsRequest/types.js, src/store/ducks/rootReducer.js
Adicionado api para obter perguntas
=> Requisição de api e adquirindo perguntas

cypress/integration/project.spec.js, src/components/Header/index.js, src/components/index.js, src/pages/Game/index.js, src/pages/Login/index.js, src/store/ducks/initialState.js, src/store/ducks/player/index.js
=> Main group req 4

cypress/integration/project.spec.js, src/actions/fetch.js, src/actions/index.js, src/pages/Login.js, src/reducers/fetch.js, src/reducers/index.js
=> [ grupo 18] cria botao iniciar jogo

src/App.js, src/actions/scoreAction.js, src/components/Question.css, src/components/Question.js, src/components/Timer.js, src/pages/Feedback.js, src/pages/Game.js, src/redux/reducers/index.js, src/redux/reducers/timerReducer.js, src/services/mockAPI.js
=> [main group 7] tudo menos 16, 17, 18

src/App.js, src/actions/index.js, src/index.js, src/pages/Game.js, src/pages/Logins.js, src/reducers/Header.js, src/reducers/index.js, src/store/index.js
=> requisito 2

cypress/integration/project.spec.js, src/pages/Game.js, src/pages/Login.js
A action getUser estava recebendo os parametros trocados
=> [GRUPO 17] Correção do dispatch getUser

src/App.js, src/pages/Ranking/index.js
** o que foi feito **
- criei a pagina de Ranking
- populei os rankings com a key rankings do localStorage
- não passou nenhum requisito por que precisa de popular a key ranking no localStora (em algum requisito anterior)
=> [ Group 3 ] - Luiz

src/actions/index.js, src/actions/playerAction.js, src/components/Header/index.js, src/pages/Login/index.js, src/reducers/index.js, src/reducers/player.js
Criação do Header contendo:
- Avatar do Gravatar
- Nome
- Score
=> Main group 3 - Header

src/pages/Login.js, src/pages/Settings.js, src/routes/index.js
Criação da página de configurações e implementação da sua rota
=> feat: config

src/App.js, src/pages/Feedback.js, src/pages/GamePage.js, src/pages/Ranking.js, src/redux/actions.js
Adiantei a estrutura dos Requisitos 13, 14, 15, 16 e 18, mas não passam porque é preciso implementar o botão Next primeiro.
=> Adiantando Requisitos 13, 14, 15, 16 e 18

cypress/integration/project.spec.js, src/App.js, src/pages/Feedback.js, src/pages/GamePage.js, src/pages/Ranking.js
Funcionalidade de botões na página de jogo, fluxo de páginas, atualização de ranking.
=> [GROUP 30] Main group 30 fixing reqs

package-lock.json, package.json, src/actions/index.js, src/pages/Login.jsx, src/reducers/asyncGravatar.js, src/reducers/asyncReducer.js, src/reducers/asyncToken.js, src/store/index.js
npm install cryptojs
criada action
criada reducer
criada fn chamada api
=> [MAIN-GROUP-15][Gravatar]

src/pages/Game/CorrectAnswer.js, src/pages/Game/Timer.js, src/pages/Game/WrongAnswer.js, src/pages/Game/index.js, src/redux/actions/index.js, src/redux/reducers/index.js, src/redux/reducers/throwTimer.js
Falta realizar as seguintes implementações:
=> [Grupo 32] Requisito 08

src/App.js, src/pages/Feedback/index.js, src/pages/Ranking/index.js
** o que foi feito **
Como a pagina de FeedBack era pequena, eu fiz todos os requisitos dela juntos.
OBS: os tests não estão passando por que é necessário que o component Game chame a rota /feedback, quando o jogar finalizar as perguntas
=> [ Group 3 ] - requisitos do 12 ao 18

cypress/integration/project.spec.js, src/components/Questions/Questions.css, src/components/Questions/index.js
=> requisito 7

src/App.js, src/Components/Questions.js, src/Pages/QuestionsPage.js, src/actions/actionsTypes.js, src/actions/index.js, src/reducers/index.js, src/reducers/questions.js
=> Main group 35 questions page

src/pages/Login/index.js
Correção do gravatar e transformação em md5
=> Main group 3

cypress/integration/project.spec.js, src/pages/Questions.css, src/pages/Questions.js
Mudar as bordas das respostas, se correta fica verde e vermelha caso seja incorreta
=> [GRUPO 17] Req 7 Borda das respostas

cypress/integration/project.spec.js, src/components/Questions/index.js
=> requisito 8

package-lock.json, package.json, src/actions/index.js, src/components/Answer.jsx, src/components/Header.jsx, src/components/Login.js, src/components/Question.jsx, src/pages/Feedback.jsx, src/pages/Game.jsx, src/pages/index.js, src/reducers/playerInfo.js, src/services/callAPI.js, src/store/index.js
Requisito 5 ainda em implementação
=> [GROUP 16] Requisito 5

src/App.test.js, src/pages/Game.jsx
Setar o estado dos botões de reposta de acordo com o tempo e a resposta
do usuário, para habilita-los e desabilita-los.
=> Configuração dos botões de resposta

src/components/Header.jsx, src/components/Trivia.jsx, src/pages/Login.jsx, src/pages/Play.jsx, src/redux/actions/index.js, src/redux/reducers/index.js, src/redux/reducers/play.js, src/services/api.js
* Requisição a API do TRIVIA e renderização das perguntas.
=> Requisito 5

src/components/Answer.css, src/components/Answer.jsx, src/components/Question.jsx, src/pages/Feedback.jsx
###########################
- Adicionado novo estado 'clicked' ao componente 'Question';
- Adicionada função para, no clique das respostas, o estado ser alterado de um string vazio para o string 'clicked';
- Adicionada classes as respostas;
- Vinculadas classes das respostas com o estado 'clicked' do componente 'Question';
- Adicionado estilo para a resposta correta e as incorretas baseadas em sua classe;
=> [GROUP 16] Requisito 7

src/App.css, src/components/Quiz.js
Implementação das bordas coloridas nas respostas
=> [ Group 3 ] Requisito 7

src/components/Trivia.jsx, src/pages/Login.jsx, src/redux/actions/index.js, src/redux/reducers/play.js
* Renderização de 1 pergunta por vez
=> Main group 12 one question screen

cypress/integration/project.spec.js, src/pages/Feedback.js
Exibição das mensagem na tela de feedback de acordo com a pontuação do jogador.
=> [GRUPO 17] Req. 13 Feedback message

src/actions/index.js, src/components/Answer.jsx, src/components/Timer.jsx, src/pages/Feedback.jsx, src/pages/Game.jsx, src/reducers/changeColor.js, src/reducers/index.js, src/reducers/timer.js
########################
- Alterada lógica do componente 'Answer', gerenciando o estado pelo redux ao invés de gerenciá-lo pelo componente pai;
- Criado componente 'Timer';
- Criada função no componente 'Timer' que desabilita as respostas depois de 30 segundos caso nenhuma resposta tenha sido clicada;
=> [GROUP 16] Requisito 8

src/components/Header.jsx, src/components/Trivia.jsx
Alterando as bordas das respostas erradas e da resposta correta.
=> Main group 12 requisito 7

src/App.js, src/Components/Questions.js, src/Pages/QuestionsPage.js, src/actions/index.js, src/pages/Login.js, src/reducers/questions.js
=> resolução requisito 5

src/App.css, src/Components/LoginForm.js
- Adição de placeholders nos inputs
- Alterações no CSS
=> Adding Placeholders

src/pages/Game.jsx, src/reducers/changeColor.js
########################
- Adicionada nova chave no reducer 'changeColor' para controlar quando qualquer botão de respostas é clicado;
- Adicionada lógica na página 'Game' para renderizar botão de próxima pergunta assim que uma das questões é clicada;
=> [GROUP 16] Requisito 10

src/App.js, src/Pages/Feedback.js, src/Pages/Game.js, src/Pages/Login.js, src/actions/index.js, src/actions/player.js, src/components/Header.js, src/components/Ranking.js, src/reducers/player.js
=> Main group 29 new branch

src/App.js, src/actions/index.js, src/components/GameHeader.js, src/pages/Feedbacks.js, src/pages/Game.js, src/reducers/game.js, src/reducers/login.js, src/style/game.css
Requisitos 10 e 13 implementados.
=> [Grupo 18] [Requisitos 10 e 13]

cypress/integration/project.spec.js, src/pages/Feedback.js
Requisito onde é exibido na tela a pontuação e os acertos
=> [GRUPO 17] Req 14 Feedback score and assertions

src/components/Header.js, src/pages/FeedBack.js, src/pages/GameScreen.js, src/store/ducks/Score/actions.js, src/store/ducks/Score/index.js, src/store/ducks/Score/types.js, src/store/ducks/rootReducer.js
Criado score ao acertar pergunta.
=> Main group 20 req 9

cypress/integration/project.spec.js, src/actions/index.js, src/pages/Game.js
PRIORIDADE 3 - A página deve conter um timer que com o tempo máximo de 30 segundos para responder, caso ultrapasse o tempo, a pergunta é considerada errada
Observações técnicas
Caso a pergunta não seja respondida a tempo, a resposta é considerada como errada
Respostas incorretas não somam pontos ao placar
Um temporizador deve aparecer na tela da pessoa, começando de 30 segundos e indo de forma decrescente até zero
Após o tempo se esgotar, todos os botões das alternativas devem ser desabilitados
Dica: Lembre-se do setTimeout e do setInterval
O que será avaliado
Aguarda 5 segundos e responde a alternativa correta
Aguarda mais de 30 segundos para responder
=> Contador feito e disable dos botões - 13/01/2021

src/App.css, src/App.js, src/components/Quiz.js, src/pages/GamePage.js
- criamos o botão proxima questao
- criamos o placar
=> [ Main group 3 ] requisito 9 requisito 10

src/actions/index.js, src/pages/Game.js, src/pages/Logins.js, src/pages/componentes/Loading.jsx, src/pages/componentes/QuestionsList.jsx, src/reducers/index.js, src/reducers/player.js, src/store/index.js
Apos Corrigir as issues do ESlint em apenas algumas questões não esta renderizando os botoes da resposta, fazendo assim não passar o requisito 6, alem disso o req 5 precisa ter uma alternativa ao setTimeOut. OBS: O uso de key solicitado pelo ESlint e as alterações na função shuffle em QuestionsList pode ser um dos motivos deste problema.
=> Main group 34 req5

src/components/Quiz.js
- foi adicionado no localStorage o ranking
- foi feito a ordenação dos ranking;
=> [ Main group 3 ] - update requisito

src/pages/Game.js
=> [grupo 18] Requisito 8 feito

src/Actions/gravatar.js, src/Actions/index.js, src/Actions/user.js, src/Components/Header.js, src/Components/LoginForm.js, src/Pages/PlayGame.js, src/Reducers/gravatar.js, src/Reducers/index.js, src/Reducers/user.js, src/Store/index.js
- Configuração dos dados do Gravatar no Redux (Actions/gravatar e Reducers/gravatar);
- Componente User renomeado para Header;
- Header traz o avatar do Gravatar;
=> Commitando requisito 4 com gravatar

cypress/integration/project.spec.js, src/pages/Game.js, src/pages/Login.js, src/pages/Questions.js, src/services/Api.js, src/services/QuestionsRequest.js
=> Feature main group 33/req5 questions

src/Pages/Feedback.js, src/Pages/Game.js, src/Pages/Login.js, src/actions/player.js, src/actions/question.js, src/components/Header.js, src/components/Questions.js, src/store/index.js
=> [GROUP 29] Req 5 e 6

src/pages/Feedbacks.js
##Requisito 15- botão para o usuário jogar novamente
=> [ grupo 18] requisito quinze

src/Pages/Feedback.js, src/Pages/Login.js, src/components/Header.js, src/components/Questions.js, src/components/Ranking.js, src/reducers/player.js, src/reducers/ranking.js
=> Main group 29 

src/pages/componentes/QuestionsList.jsx
=> [Grupo 34] time out

src/App.js, src/pages/Feedbacks.js, src/pages/Ranking.js
=> [grupo 18]  requisito 16 feito

src/App.css, src/pages/componentes/QuestionsList.jsx
7. Desenvolva o estilo que, ao clicar em uma resposta, a correta deve ficar verde e as incorretas, vermelhas
=> Main group 34 rq7

src/pages/Ranking.js
=> [grupo 18] requisito 18

src/components/Quiz.js, src/components/Timer.js, src/pages/GamePage.js
Timer regressivo de 30 segundos - configurado
Após 30 segundos, os botões devem ficar desabilitados - feito
=> Main group 3 

src/pages/componentes/QuestionsList.jsx
=> [Grupo 34] adicionando botao de proxima pergunta

cypress/integration/project.spec.js, src/actions/index.js, src/components/GameHeader.js, src/pages/Feedbacks.js, src/pages/Game.js, src/reducers/game.js, src/services/index.js
Requisito 14 sem dados do score (requisito 11 passou junto)...
=> [Grupo 18] [Requisito 14 - Resultados na tela de feedback]

debug.log, src/components/Header/index.js, src/components/Quiz/index.js, src/components/Timer/index.js, src/pages/Login/index.js
- foi adicionado o localStorage do key state; (no Login e no Quiz), pois era isso que tava dando erro no 9, 11 e 14
- foi consertada a propTypes do count que o Quiz recebia de bool para number
- removi o texto de "Placar" da <p></p> do score, pois era isso que estava dando erro no 12
=> [ Main group 3 ] - implementations

src/App.js, src/actions/index.js, src/pages/Feedback.js, src/pages/Game.js
PRIORIDADE 2 - O jogo deve ser composto por 5 perguntas, onde, a cada nova pergunta, o timer é reiniciado e após respondê-las, a pessoa que joga deve ser redirecionada para a tela de feedback
Observações técnicas
A cada nova pergunta o temporizador deve ser reiniciado para 30 segundos
Após a quinta pergunta, o botão "Próxima" deve redirecionar a pessoa para a tela de Feedback
Para perguntas com type:"boolean", mostrar somente 2 campos (um para cada resposta possível)
Para perguntas com type:"multiple", mostrar a quantidade necessária de campos (um para cada resposta possível)
O que será avaliado
Acerta todas as perguntas
Erra todas as perguntas
Redireciona para a tela de feedback após a quinta pergunta
=> Main group 36 req11

src/Components/Header.js, src/Components/Questions.js, src/actions/actionsTypes.js, src/actions/index.js, src/reducers/index.js, src/reducers/score.js
=> Main group 35 req9

src/App.css, src/Components/Answer.jsx, src/Components/Question.jsx, src/Components/QuestionForm.jsx, src/pages/Play.jsx, src/reducers/asyncGravatar.js
Request the API to receive the questions and population of the question form.
=> [GROUP-15][REQUIREMENT-05-06][GET-QUESTIONS-GAME-SCREEN]

src/pages/Ranking.js
=> Requisito 18 resolvido

src/actions/index.js, src/components/Answer.jsx, src/components/NextQuestionButton.jsx, src/components/Timer.jsx, src/pages/Feedback.jsx, src/pages/Game.jsx, src/pages/Ranking.jsx, src/pages/Settings.js, src/reducers/index.js, src/reducers/questions.js, src/services/callAPI.js
############################
- Refatorado o código de modo que as questões fiquem armazenadas na store;
- Implementados dropdowns na página 'Settings' que permitem selecionar dificuldade, tipo de perguntas e categoria;
- Criado novo componente 'NextQuestionButton';
- Trocado quase todos os por , mantendo apenas o do componente 'NextQuestionButton';
=> [GROUP 16] Requisitos 19, 20 e 21

package-lock.json, src/Pages/Feedback.js, src/components/Header.js
=> [GRUPO 29] Página de Feedback

src/Components/Questions.js
=> Main group 35 req12

src/pages/Game.js, src/pages/Logins.js, src/pages/componentes/Header.jsx, src/pages/componentes/QuestionsList.jsx, src/store/index.js
Em desenvolvimento, problemas em fazer o score ser encontrado pelo Cypress pois nao consigo settar o localStorage igual o solicitado no readMe.
=> Main group 34 requisito9

src/components/GameHeader.js, src/pages/Game.js
Alterações de css e alterações para passar no cypress.
=> [GROUP 36][CSS]

src/components/Questions.js
=> [GROUP 29] Merges dos requisitos

src/App.js, src/Pages/Login.js, src/Pages/Ranking.js, src/Pages/Settings.js
Mudança de nomenclatura: Config (configuracoes) para Settings
=> [GRUPO 29] Settings

src/App.js, src/Pages/Ranking.js
=> [GRUPO 29] Ranking Button

src/actions/index.js, src/pages/Game.js, src/reducers/game.js
Lógica para evitar embaralhamento de respostas cada vez que o componente atualiza...
=> [Grupo 18] [Correção de bug no embaralhamento de respostas]

cypress/integration/project.spec.js, src/components/Questions.js, src/pages/Game.css, src/pages/Game.js
=> Main group 23 requisito 10

src/App.css, src/Components/Answer.jsx, src/Components/QuestionForm.jsx, src/pages/Play.jsx
Ao responder a pergunta, se a alternativa for correta, deve ficar verde, caso contrário, vermelha
Observações técnicas
Utilize a propriedade css border com o valor 3px solid rgb(6, 240, 15) para a alternativa correta.
Utilize a propriedade css border com o valor 3px solid rgb(255, 0, 0) para as alternativas incorretas.
=> [Group 15] Requisito 7 - estilo da escolha do click

package-lock.json, package.json, src/components/HomeButton.jsx, src/css/header.css, src/index.js, src/pages/feedback.js, src/pages/header.js, src/pages/login.js, src/pages/play.js, src/pages/question.css, src/pages/ranking.jsx
Instalado semantic ui e importado nas páginas.
=> Main group 28 css

cypress/integration/project.spec.js, package-lock.json, package.json, src/actions/index.js, src/pages/Login.js, src/pages/TelaDeJogo.js, src/routes/index.js
=> Main group 2 requisito 5

src/actions/index.js, src/pages/Login.js, src/pages/TelaDeJogo.js, src/reducers/player.js
=> Resolução dos requisitos 4 e 5

src/pages/Game.css, src/pages/Game.js
Refatoração com correção de lint
=> [Main group 23] requisito 10

src/components/Header.js, src/components/Questions.js, src/pages/Login.js
Corrigindo lint e conflitos e acrescentando o teste 2 requisito 9. Grupo 23.
=> Main group 23 requisito 9

src/App.js, src/Components/PlayAgain.js, src/Components/Timer.js, src/Pages/Feedback.js, src/Pages/PlayGame.js, src/Store/index.js
* [8]. Desenvolva um timer onde a pessoa que joga tem 30 segundos para responder;
* [15]. Crie a opção para a pessoa jogadora poder jogar novamente;
* Alteração do state do LoginForm pra corrigir a renderização;
=> Commitando timer do req 8, fix do state LoginForm e req 15

src/components/FeedbackScore/FeedbackScore.css, src/components/FeedbackScore/index.js, src/components/Header/Header.css, src/components/Header/index.js, src/components/Questions/Questions.css, src/components/Questions/index.js, src/pages/FeedBack/FeedBack.css, src/pages/FeedBack/index.js
Colocando CSS na pagina login, Game e Feedback
=> Main group 27 req 9

src/App.js, src/Components/GoHome.js, src/Components/GoRanking.js, src/Pages/Feedback.js, src/Pages/PlayGame.js, src/Pages/Ranking.js
* [15] . Crie a opção para a pessoa jogadora poder jogar novamente;
* [16]. Crie a opção para a pessoa jogadora poder visualizar a tela de ranking;
* Crie a tela de ranking (obs: criada somente para testar o botao).
=> Commitando os botoes dos req 15, 16 e pagina de ranking pra simulacao

src/css/Button.css, src/pages/TelaDeJogo.js
=> Adicionando requisito 7

cypress/integration/project.spec.js, src/App.js, src/components/Header.js, src/components/Questions.js, src/pages/Feedback.js, src/pages/Game.js, src/pages/Ranking.js, src/pages/index.js
=> Main group 23 requisito 11

src/pages/TelaDeJogo.js, src/pages/Timer.js
=> Main group 02 requisito 8

cypress/integration/project.spec.js, src/Components/QuestionForm.jsx, src/pages/Play.jsx
Gente, eu errei no nome da branch... essa é a branch do **requisito 10**
=> [Group 15] Requisito 10

src/actions/index.js, src/components/Answer.jsx, src/components/Clock.jsx, src/components/Login.js, src/components/NextQuestionButton.jsx, src/components/RankingItem.jsx, src/components/Timer.jsx, src/pages/Feedback.jsx, src/pages/Game.jsx, src/pages/Ranking.jsx, src/reducers/playerInfo.js, src/reducers/timer.js
###########################
- Adicionada condicional dentro da função 'setStorage' no componente 'Answer';
=> [GROUP 16] Requisito 14

src/actions/index.js, src/components/Answer.jsx, src/components/Clock.jsx, src/components/Login.js, src/components/NextQuestionButton.jsx, src/components/RankingItem.jsx, src/components/Timer.jsx, src/pages/Feedback.jsx, src/pages/Game.jsx, src/pages/Ranking.jsx, src/reducers/playerInfo.js, src/reducers/timer.js
Implementados requisitos faltantes, porém projeto não passa no avaliador local
=> [GROUP 16] Finalizando projeto

package-lock.json, package.json, src/Components/LoginForm.js, src/Components/Questions.js, src/Pages/PlayGame.js, src/Store/index.js
- Requisito 5 renderizando as perguntas, mas sem passar no teste.
=> requirement 5

cypress/integration/project.spec.js, src/components/Header.js, src/pages/Feedback.js, src/pages/Ranking.js
Requisitos 15, 16 e 18 EsLint ok Cypress ok. Grupo 23.
=> Main group 23 requisito 17 parte 2

cypress/integration/project.spec.js, src/actions/index.js, src/components/GameHeader.js, src/pages/Feedback.js, src/pages/Game.js, src/pages/Login.js, src/reducers/score.js, src/reducers/user.js
Requisitos 12-16, página de feedback.
=> [GROUP 36][REQ12-16]

src/App.css, src/components/GameBoard.jsx, src/components/Question.jsx
Elaborado style css dinamico para quando o usuario clicar no botão e esse receber estilo de cor vermelha nos botões de respostas incorretas e verde na correta.
=> Main group 13 v8

src/App.css, src/components/Header.js, src/components/Questions.js, src/pages/EndGame.js, src/pages/Feedback.js, src/pages/Login.js
Alunos: Herika Strongreen, Rafael Alstent, Andre Menezes e Jessica de Paula
=> Grupo 23: Pague 1 Leve 2

src/Components/Questions.js, src/Pages/PlayGame.css, src/Pages/PlayGame.js, src/Store/index.js
[7]. Desenvolva o estilo que, ao clicar em uma resposta, a correta deve ficar verde e as incorretas, vermelhas;
[8]. Desenvolva um timer onde a pessoa que joga tem 30 segundos para responder;
[10]. Crie um botão de "próxima" que apareça após a resposta ser dada;
=> Commitando os reqs 7, 8 e 10

package-lock.json, package.json, src/App.js, src/actions/index.js, src/index.css, src/index.js, src/pages/Login.css, src/pages/Login.js, src/pages/Settings.js, src/reducers/index.js, src/reducers/player.js, src/store/index.js
=> [GROUP 10] Requisitos 1 e 2

src/Routes.jsx, src/pages/Feedback.jsx, src/pages/Ranking.jsx
* O botão para redirecionar o jogador para tela de ranking.
=> Main group 12 ranking button

cypress/integration/project.spec.js, src/Components/QuestionForm.jsx, src/pages/Feedback.jsx, src/pages/Login.jsx, src/pages/Play.jsx, src/pages/Ranking.jsx
criada função scorePoint, para atualizar o localStorage chaves state.player.score e ranking.score.
=> [main-group-15][Requisito 9]

cypress/integration/project.spec.js, src/pages/Feedback.jsx, src/pages/Ranking.jsx
Por enquanto está hard-code, estou aguardando LocalStorage.
=> [Main-group-15][Tela ranking requisitos 16,17 e 18]

cypress/integration/project.spec.js, src/pages/Feedback.jsx, src/pages/Ranking.jsx
Validação de estrutura e requisitos obrigatórios
=> [main-group-15][Requisito 17 e 18]Tela Ranking

src/pages/Play.jsx, src/pages/Ranking.jsx
=> [Group 15] Requisito 11

src/Actions/index.js, src/Actions/score.js, src/Components/Header.js, src/Components/LoginForm.js, src/Components/PlayAgain.js, src/Components/Questions.js, src/Reducers/index.js, src/Reducers/score.js, src/Reducers/user.js
- Atualiza placar quando o jogador acerta a resposta;
- Na página de Feedback, reseta o placar e todas as informações do jogador quando ele clica em "Jogar Novamente";
=> Requirement 9

src/components/Header.jsx, src/components/Trivia.jsx, src/pages/Feedback.jsx, src/pages/Login.jsx, src/pages/Ranking.jsx, src/redux/actions/index.js, src/redux/reducers/login.js, src/redux/reducers/play.js, src/services/api.js
* Lista dos jogadores em ordem decrescente.
=> Main group 12 ranking screen - Requisito 17

src/Components/Header.js, src/Pages/Feedback.js
- Atualização do estado da quantidade de questões que o jogador acertou para que a condição que define a mensagem de feedback funcione - Componente Feedback;
- Retirada da palavra Score do paragrafo que retorna o score e deixando apenas o número salvo no estado - Componente Header;
=> Requisitos da tela de Feedback

src/Components/QuestionForm.jsx, src/actions/index.js, src/pages/Play.jsx, src/pages/Ranking.jsx, src/reducers/game.js
=> [Group 15] Requisito 13

src/Pages/Feedback.js
- Exiba as informações relacionadas aos resultados obtidos para a pessoa usuária:
* O placar final deve ser mostrado em um elemento com o atributo data-testid com o valor feedback-total-score;
* O número de perguntas que a pessoa acertou deve ser exibido em um elemento com o atributo data-testid com o valor feedback-total-question.
=> Commitando requisito 14
